USE [master]
GO

/****** Object:  Database [SteelThread]    Script Date: 3/13/2018 9:34:40 PM ******/
CREATE DATABASE [SteelThread]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SteelThread', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\SteelThread.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SteelThread_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\SteelThread_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [SteelThread] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SteelThread].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SteelThread] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SteelThread] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SteelThread] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SteelThread] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SteelThread] SET ARITHABORT OFF 
GO

ALTER DATABASE [SteelThread] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SteelThread] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SteelThread] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SteelThread] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SteelThread] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SteelThread] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SteelThread] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SteelThread] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SteelThread] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SteelThread] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SteelThread] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SteelThread] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SteelThread] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SteelThread] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SteelThread] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SteelThread] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SteelThread] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SteelThread] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SteelThread] SET  MULTI_USER 
GO

ALTER DATABASE [SteelThread] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SteelThread] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SteelThread] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SteelThread] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SteelThread] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SteelThread] SET QUERY_STORE = OFF
GO

USE [SteelThread]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [SteelThread] SET  READ_WRITE 
GO

